### ISSUE TITLE
Project missing in Projects Overview when using same path as next project

### ISSUE THREAD

**Issue by stefan-cukl** [infracost/vscode-infracost#209]
Having 2 projects with the same path will result in only the last one being displayed in the projects overview:
![image](https://github.com/infracost/vscode-infracost/assets/34101294/9e7c1b3f-5af5-40e3-a605-4ab7c392e1c7)

but when running `infracost breakdown --config-file infracost.yml` both of them are displayed:
![image](https://github.com/infracost/vscode-infracost/assets/34101294/4de4978d-2119-4844-ab67-5cc0f93b43cf)

`infracost.yml`
```
version: 0.1
projects:
  - name: sapbo-prod
    path: terraform/sapbo
    terraform_var_files:
      - ../environments/prod.tfvars

  - name: sapbo-dev
    path: terraform/layers/sapbo
    terraform_var_files:
      - ../environments/dev.tfvars
```
